# Helper script to generate man page from .in template
# Usage: cmake -DINPUT=... -DOUTPUT=... -DMAN_VERSION=... -DDATE=...
#        -DSYSCONFDIR=... -DLIBEXECDIR=... -DPKGLIBEXECDIR=... -DPKGDATADIR=... -P generate-man.cmake
if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "INPUT and OUTPUT must be defined")
endif()
file(READ "${INPUT}" _content)
if(DEFINED DATE)
    string(REPLACE "%DATE_OF_MAN_PAGE%" "${DATE}" _content "${_content}")
endif()
if(DEFINED MAN_VERSION)
    string(REPLACE "%MAN_VERSION%" "${MAN_VERSION}" _content "${_content}")
endif()
if(DEFINED SYSCONFDIR)
    string(REPLACE "%sysconfdir%" "${SYSCONFDIR}" _content "${_content}")
endif()
if(DEFINED LIBEXECDIR)
    string(REPLACE "%libexecdir%" "${LIBEXECDIR}" _content "${_content}")
endif()
if(DEFINED PKGLIBEXECDIR)
    string(REPLACE "%pkglibexecdir%" "${PKGLIBEXECDIR}" _content "${_content}")
endif()
if(DEFINED PKGDATADIR)
    string(REPLACE "%pkgdatadir%" "${PKGDATADIR}" _content "${_content}")
endif()
file(WRITE "${OUTPUT}" "${_content}")
