name: ci-alpine

on:
  workflow_call:

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    container:
      image: alpine:latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          apk add build-base cmake ninja pkgconf samurai sudo
          apk add aspell-dev check-dev e2fsprogs-dev gettext-dev glib-dev gpm-dev libssh2-dev perl slang-dev

      - name: Build default configuration
        run: |
          adduser --home "$(pwd)" --no-create-home --disabled-password test
          chown -R test "$(pwd)"

          su - test -c ' \
            cmake -S . -B build -G Ninja \
              -DCMAKE_INSTALL_PREFIX="$(pwd)/install-prefix" \
              -DMC_ENABLE_WERROR=ON \
              -DMC_ENABLE_TESTS=ON \
              && \
            \
            cmake --build build -j$(nproc) && \
            ctest --test-dir build --output-on-failure  && \
            cmake --install build \
          '

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-suite-logs-alpine
          path: build/**/Testing/**/*.log
