name: ci-macos

on:
  workflow_call:
    inputs:
      CFLAGS:
        description: 'Custom CFLAGS'
        default: ''
        required: false
        type: string

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 5

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          brew install cmake ninja pkg-config gettext check
          brew install aspell e2fsprogs glib libssh2 openssl s-lang

          # unzip is part of the base system

      - name: Build default configuration
        run: |
          export CFLAGS="${{ inputs.CFLAGS }}"

          cmake -S . -B build -G Ninja \
            -DCMAKE_INSTALL_PREFIX="$(pwd)/install-prefix" \
            -DMC_ENABLE_WERROR=ON \
            -DMC_ENABLE_TESTS=ON

          cmake --build build -j$(sysctl -n hw.logicalcpu)
          ctest --test-dir build --output-on-failure
          cmake --install build

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-suite-logs-macos
          path: build/**/Testing/**/*.log
